-- SQL Script to seed authentication data for SchoolSync
-- Run this script against your SMSPrototype2 database

-- Insert a demo school
DECLARE @SchoolId UNIQUEIDENTIFIER = NEWID();

INSERT INTO Schools (Id, RegistrationNumber, Name, Email, Phone, Address, City, State, PinCode, Subscription, SubscriptionDate, IsSoftDeleted)
VALUES (@SchoolId, 'SCH001', 'Demo School', 'demo@school.com', '1234567890', '123 School Street', 'Demo City', 'Demo State', 123456, 1, GETDATE(), 0);

-- Insert Roles (if not exists)
IF NOT EXISTS (SELECT 1 FROM AspNetRoles WHERE Name = 'SuperAdmin')
    INSERT INTO AspNetRoles (Id, Name, NormalizedName) VALUES (NEWID(), 'SuperAdmin', 'SUPERADMIN');

IF NOT EXISTS (SELECT 1 FROM AspNetRoles WHERE Name = 'Admin')
    INSERT INTO AspNetRoles (Id, Name, NormalizedName) VALUES (NEWID(), 'Admin', 'ADMIN');

IF NOT EXISTS (SELECT 1 FROM AspNetRoles WHERE Name = 'Teacher')
    INSERT INTO AspNetRoles (Id, Name, NormalizedName) VALUES (NEWID(), 'Teacher', 'TEACHER');

IF NOT EXISTS (SELECT 1 FROM AspNetRoles WHERE Name = 'Student')
    INSERT INTO AspNetRoles (Id, Name, NormalizedName) VALUES (NEWID(), 'Student', 'STUDENT');

IF NOT EXISTS (SELECT 1 FROM AspNetRoles WHERE Name = 'Parent')
    INSERT INTO AspNetRoles (Id, Name, NormalizedName) VALUES (NEWID(), 'Parent', 'PARENT');

-- Insert Users with hashed password (Password@123)
-- Note: Password hash for "Password@123" - you'll need to generate proper hash using Identity
DECLARE @SuperAdminId UNIQUEIDENTIFIER = NEWID();
DECLARE @AdminId UNIQUEIDENTIFIER = NEWID();
DECLARE @TeacherId UNIQUEIDENTIFIER = NEWID();
DECLARE @StudentId UNIQUEIDENTIFIER = NEWID();
DECLARE @ParentId UNIQUEIDENTIFIER = NEWID();

-- Password hash for "Password@123" generated by ASP.NET Core Identity
-- AQAAAAIAAYagAAAAEHn... is a sample, in reality we need the app to generate it
DECLARE @PasswordHash NVARCHAR(MAX) = 'AQAAAAIAAYagAAAAEHnFdWe3wQk8RgkqHLCj/bTBdJXaQtJvFcJJ2tZq6jKQZQCGqKJZ0vHqJKQZQCGqK==';

INSERT INTO AspNetUsers (Id, UserName, NormalizedUserName, Email, NormalizedEmail, EmailConfirmed, PasswordHash, SecurityStamp, ConcurrencyStamp, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEnabled, AccessFailedCount, SchoolId, CreatedDate)
VALUES 
    (@SuperAdminId, 'superadmin@school.com', 'SUPERADMIN@SCHOOL.COM', 'superadmin@school.com', 'SUPERADMIN@SCHOOL.COM', 1, @PasswordHash, NEWID(), NEWID(), 0, 0, 1, 0, @SchoolId, GETDATE()),
    (@AdminId, 'admin@school.com', 'ADMIN@SCHOOL.COM', 'admin@school.com', 'ADMIN@SCHOOL.COM', 1, @PasswordHash, NEWID(), NEWID(), 0, 0, 1, 0, @SchoolId, GETDATE()),
    (@TeacherId, 'teacher@school.com', 'TEACHER@SCHOOL.COM', 'teacher@school.com', 'TEACHER@SCHOOL.COM', 1, @PasswordHash, NEWID(), NEWID(), 0, 0, 1, 0, @SchoolId, GETDATE()),
    (@StudentId, 'student@school.com', 'STUDENT@SCHOOL.COM', 'student@school.com', 'STUDENT@SCHOOL.COM', 1, @PasswordHash, NEWID(), NEWID(), 0, 0, 1, 0, @SchoolId, GETDATE()),
    (@ParentId, 'parent@school.com', 'PARENT@SCHOOL.COM', 'parent@school.com', 'PARENT@SCHOOL.COM', 1, @PasswordHash, NEWID(), NEWID(), 0, 0, 1, 0, @SchoolId, GETDATE());

-- Assign roles to users
INSERT INTO AspNetUserRoles (UserId, RoleId)
SELECT @SuperAdminId, Id FROM AspNetRoles WHERE Name = 'SuperAdmin'
UNION ALL
SELECT @AdminId, Id FROM AspNetRoles WHERE Name = 'Admin'
UNION ALL
SELECT @TeacherId, Id FROM AspNetRoles WHERE Name = 'Teacher'
UNION ALL
SELECT @StudentId, Id FROM AspNetRoles WHERE Name = 'Student'
UNION ALL
SELECT @ParentId, Id FROM AspNetRoles WHERE Name = 'Parent';

PRINT 'Seed data inserted successfully!';
PRINT 'Login Credentials:';
PRINT 'SuperAdmin: superadmin@school.com / Password@123';
PRINT 'Admin: admin@school.com / Password@123';
PRINT 'Teacher: teacher@school.com / Password@123';
PRINT 'Student: student@school.com / Password@123';
PRINT 'Parent: parent@school.com / Password@123';
